config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'home#index', as: :home

  resources :locations
  resources :articles
  devise_for :users
  resources :users
  # Semi-static page routes

  
  # Set the root url
  root :to => 'home#index'  
end

app/views/partials/_article_content.erb
        <div class="left_column floatleft">
          <div class="single_left_column_wrapper">
            <h1 class="title"><%= @article.title %></h1>
            <h3> <%= @article.date %> </h3>
            <p id="notice"><%= notice %></p>
<p>
  <strong>Source:</strong>
  <%= @article.source %>
</p>
<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>

  <%= @article.description %>
</p>



<p>
  <strong>Consensus:</strong>
  <%= @article.consensus %>
</p>


<p>
  <strong>Political Impartiality:</strong>
  <%= @article.political %>
</p>

<p>
  <strong>Emotional Neutrality:</strong>
  <%= @article.emotional %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

            
            
          </div>
        </div>

app/views/partials/_footer.html.erb
    <div class="footer_bottom_area">
      <div class="footer_menu">
        <ul id="f_menu">
          <li><a href="#">Trending</a></li>
          <li><a href="#">World</a></li>
          <li><a href="#">Pittsburgh</a></li>
          <li><a href="#">Politics</a></li>
          <li><a href="#">Tech</a></li>
          <li><a href="#">Entertainment</a></li>
          <li><a href="#">Health</a></li>
          <li><a href="#">Sports</a></li>
          <li><a href="#">Science</a></li>
          <li><a href="#">Opinion</a></li>
        </ul>
      </div>
      <div class="copyright_text">
        <p>Copyright &copy; 2017 GeNews. All rights reserved.</p>
      </div>
    </div>

app/views/partials/_navigation.html.erb
      <ul id="nav">
        <li><a href="#">Trending</a>
          <ul>
          <%for article in Article.all %>
            <li><%= link_to  article.title, article_path(article)%></li>
          <%end%>
              <ul>
               
              </ul>
            </li>
           
          </ul>
        </li>
        <li><a href="#">World</a></li>
        <li><a href="#">Pittsburgh</a>
        </li>
        <li><a href="#">Politics</a> <ul>
          <%for article in Article.all %>
            <li><%= link_to  article.title, article_path(article)%></li>
          <%end%>
              <ul>
               
              </ul>
            </li>
           
          </ul>
        </li>
        <li><a href="#">Tech</a>
          <ul>
           
              <ul>
               
              </ul>
            </li>
        
          </ul>
        </li>
        <li><a href="#">Entertainment</a></li>
        <li><a href="#">Health</a></li>
        <li><a href="#">Sports</a>
          <ul>
          
          </ul>
        </li>
        <li><a href="#">Science</a></li>
        <li><a href="#">Opinion</a></li>
      </ul>
    </div>

app/views/partials/_search.html.erb
<div class="social_plus_search floatright">
 
        <div class="search">
          <form action="#" method="post" id="search_form">
            <input type="text" value="Search news" id="s" />
            <input type="submit" id="searchform" value="search" />
            <input type="hidden" value="post" name="post_type" />
          </form>
        </div>
      </div>

app/views/partials/_top_menu.html.erb
      <div class="logo floatleft"><a href="#"><%= image_tag("logo.png") %></a></div>
      <div class="top_menu floatleft">
        <ul>
          <li><a href="index.html">Home</a></li>
          <li><a href="#">Reliability Index</a></li>
          <li><a href="#">Login</a></li>
        </ul>
      </div>